# ATVN Configuration File

# Data settings
data:
  dataset_root: "path/to/dataset"  # Root directory containing image folders
  pairs_file: "path/to/pairs.json"  # JSON file with twin pairs
  image_size: [224, 224]  # Input image size
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  num_workers: 4
  pin_memory: true

# Model settings
model:
  backbone: "facenet"  # Options: facenet, arcface, resnet50
  embedding_dim: 512
  attention_dim: 256
  num_attention_heads: 8
  dropout: 0.1
  freeze_backbone: false  # Whether to freeze pre-trained backbone
  pretrained: true

# Training settings
training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  lr_scheduler: "cosine"  # Options: cosine, step, plateau
  warmup_epochs: 5
  gradient_clip: 1.0
  
# Loss settings
loss:
  triplet_margin: 0.5
  triplet_weight: 1.0
  center_weight: 0.5
  attention_reg_weight: 0.1
  
# Optimizer
optimizer:
  type: "adamw"  # Options: adam, adamw, sgd
  momentum: 0.9  # For SGD
  betas: [0.9, 0.999]  # For Adam/AdamW
  
# Data augmentation
augmentation:
  horizontal_flip: 0.5
  rotation: 15
  color_jitter: 0.2
  gaussian_blur: 0.1
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
# Validation
validation:
  frequency: 5  # Validate every N epochs
  threshold: 0.6  # Similarity threshold for positive classification
  
# Checkpointing
checkpoint:
  save_dir: "checkpoints"
  save_frequency: 10
  save_best_only: true
  monitor: "val_accuracy"
  
# Logging
logging:
  use_wandb: false
  project_name: "nd-twin-verification"
  log_frequency: 100  # Log every N steps
  
# Hardware
device: "cuda"  # cuda or cpu
mixed_precision: true